### ISSUE TITLE
系统VPN确认对话框无法显示

### ISSUE THREAD

**Issue by jinliu** [LOSP/SwipeBack#1]
logcat:

I/ActivityManager(  743): START u0 {cmp=com.android.vpndialogs/.ConfirmDialog} from pid 4061
I/ActivityManager(  743): Start proc com.android.vpndialogs for activity com.android.vpndialogs/.ConfirmDialog: pid=8027 uid=10014 gids={50014}
D/dalvikvm( 8027): DexOpt: couldn't find field Landroid/app/ActivityThread;.mActiveResources
W/dalvikvm( 8027): VFY: unable to resolve instance field 1
D/dalvikvm( 8027): VFY: replacing opcode 0x54 at 0x0006
D/dalvikvm( 8027): DexOpt: couldn't find field Landroid/app/ActivityThread;.mPackages
W/dalvikvm( 8027): VFY: unable to resolve instance field 4
D/dalvikvm( 8027): VFY: replacing opcode 0x54 at 0x0000
E/VpnConfirm( 8027): onResume
E/VpnConfirm( 8027): android.util.AndroidRuntimeException: requestFeature() must be called before adding content
E/VpnConfirm( 8027):    at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:302)
E/VpnConfirm( 8027):    at com.android.internal.app.AlertController.installContent(AlertController.java:234)
E/VpnConfirm( 8027):    at com.android.internal.app.AlertActivity.setupAlert(AlertActivity.java:74)
E/VpnConfirm( 8027):    at com.android.vpndialogs.ConfirmDialog.onResume(ConfirmDialog.java:76)
E/VpnConfirm( 8027):    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
E/VpnConfirm( 8027):    at android.app.Activity.performResume(Activity.java:5310)
E/VpnConfirm( 8027):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2778)
E/VpnConfirm( 8027):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2817)
E/VpnConfirm( 8027):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
E/VpnConfirm( 8027):    at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/VpnConfirm( 8027):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/VpnConfirm( 8027):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/VpnConfirm( 8027):    at android.os.Looper.loop(Looper.java:136)
E/VpnConfirm( 8027):    at android.app.ActivityThread.main(ActivityThread.java:5017)
E/VpnConfirm( 8027):    at java.lang.reflect.Method.invokeNative(Native Method)
E/VpnConfirm( 8027):    at java.lang.reflect.Method.invoke(Method.java:515)
E/VpnConfirm( 8027):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/VpnConfirm( 8027):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/VpnConfirm( 8027):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
E/VpnConfirm( 8027):    at dalvik.system.NativeStart.main(Native Method)

**Comment by PeterCxy** [comment]
了解了，明天修。

**Comment by PeterCxy** [comment]
不过，你试试看是不是已经好了，因为我刚提交了一个commit，在dialog上禁用滑动返回。。
