### ISSUE TITLE
请问Android4.4.2中无法显示下面Activity的问题解决了没？

### ISSUE THREAD

**Issue by wenjiang** [LOSP/SwipeBack#6]
我们的应用使用了SwipeBack，但在Android4.4.2的手机上发现滑动时，下面的Activity无法显示，这个问题解决了没？

**Comment by PeterCxy** [comment]
这个问题在我的模块里是用hook了com.android.server里面的东西来解决的，对于app，只有一个解决方法，那就是把最底层的主Activity设为不透明
