### ISSUE TITLE
Swipe between apps

### ISSUE THREAD

**Issue by ghost** [LOSP/SwipeBack#9]
That would be great if we can swipe between apps like we can use back button with this extension.

Is this possible ? Could you make it?

**Comment by PeterCxy** [comment]
Can't it swipe between apps by now?

**Comment by ghost** [comment]
I can swipe only to the previous app if it's latest activity. My idea is to swipe between apps, to next and previous from the recents apps. That would be much better from for example switchr. I love how Swip to change activities :)

**Comment by ghost** [comment]
*How swipeBack changes the activities
